{
 "title": "Simple and fast Troubleshooting",
 "description": "Simple and fast Troubleshooting Dashboard for kubernetes ",
 "tags": [
  "infra",
  "logs",
  "pod",
  "status",
  "troubleshoot"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "query_result(kube_pod_info{})" } },
   {
    "name": "container_error",
    "label": "container_error",
    "query": {
     "query": "kube_pod_container_status_waiting_reason{namespace=\"$namespace\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Namespace $namespace details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "K8s Nodes",
   "type": "stat",
   "description": "# kubectl get nodes",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_created{})" }
   ]
  },
  {
   "title": "Total  pods",
   "type": "stat",
   "description": "# kubectl get pods -n $namespace",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Container Ready",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Container Waiting",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "PVCs Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolume_status_phase{job=\"kube-state-metrics\",phase=\"Pending\",namespace=\"$namespace\"} != 0)"
    }
   ]
  },
  {
   "title": "PVCs",
   "type": "stat",
   "description": "# Show Persisten Volumes",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "PVCs Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolume_status_phase{job=\"kube-state-metrics\",phase=\"Failed\",namespace=\"$namespace\"} != 0)"
    }
   ]
  },
  {
   "title": "Last Terminated container status reason ",
   "type": "table",
   "description": "### OOMKilled (exit code 137)\nThe OOMKilled error, also indicated by exit code 137, means that a container or pod was terminated because they used more memory than allowed. OOM stands for “Out Of Memory”.\nIf a container uses more memory than its memory limit, it is terminated with an OOMKilled status. Similarly, if overall memory usage on all containers, or all pods on the node, exceeds the defined limit, one or more pods may be terminated.\n\n# Error\nError code or Exit Code 1 means that a container terminated, typically due to an application error or an invalid reference.\n\n",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "POD Status in $namespace namespace",
   "type": "table",
   "description": "###  Similar to run:   kubectl  -n $namespace get pod -o wide\n\n\n# The CrashLoopBackOff:\n\n- Insufficient resources—lack of resources prevents the container from loading\n- Locked file—a file was already locked by another container\n- Locked database—the database is being used and locked by other pods\n- Failed reference—reference to scripts or binaries that are not present on the container\n- Setup error—an issue with the init-container setup in Kubernetes\n- Config loading error—a server cannot load the configuration file\n- Misconfigurations—a general file system misconfiguration\n- Connection issues—DNS or kube-DNS is not able to connect to a third-party service\n- Deploying failed services—an attempt to deploy services/applications that have already failed (e.g. due to a lack of access to other services)\n\n# The ImagePullBackOff:\n\nmeans that a Pod couldn’t start because Kubernetes could not pull a container image. The ‘BackOff’ part indicates that Kubernetes will keep trying to pull the image, with an increasing back-off delay.  \n- check  if image exist\n- check if image tag is correct\n- check if you have the secret to pull image from private registry\n- check if  the value \"imagePullSecrets\" is right configured in your deployment  (use GIT repo to check it)\n",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{namespace=\"$namespace\"}"
    },
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"$namespace\"}"
    },
    {
     "expr": "kube_pod_info{namespace=\"$namespace\"}"
    },
    {
     "expr": "time() - kube_pod_start_time{namespace=\"$namespace\"}"
    },
    {
     "expr": "kube_pod_container_status_waiting_reason{namespace=\"$namespace\"}"
    },
    {
     "expr": "kube_pod_container_info{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Last 100  logs from all containers",
   "type": "logs",
   "description": "Similar to:    kubectl logs pod \n- You can see logs of any pod\n-\n\nFor more info use dashboards\n-\n- Default / Logs by App\n\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\"} !~ \"(?i)kube-probe\" !~ \"(?i)Blackbox Exporter\" ",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "Pods Not running reason",
   "type": "table",
   "description": "# Waiting reason\npods not running, this status is caused because pod can't terminate of start for any reason. (see Reason)\n\n# ImagePullBackOff or ErrImagePull:\nmeans that a Pod couldn’t start because Kubernetes could not pull a container image. The ‘BackOff’ part indicates that Kubernetes will keep trying to pull the image, with an increasing back-off delay.  \n\n# CrashloopBackOff \nIts means that you have a pod starting, crashing, starting again, and then crashing again.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting_reason{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Last 100  logs from container [ $container_error ] error",
   "type": "logs",
   "description": "Similar to:    kubectl logs pod \n- \n-\n\nFor more info use dashboards\n-\n- Default / Logs by App\n\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", container=\"$container_error\"}| json | line_format \"{{ .app }} - {{ .log }}\"",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "Persistent Volume Claim in namespace:  $namespace",
   "type": "table",
   "description": "###  Similar to:  kubectl -n $namespace describe VOLUME-NAME",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (persistentvolumeclaim,namespace,storageclass,volumename) (kube_persistentvolumeclaim_info{namespace=\"$namespace\"})"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"})"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=\"$namespace\"})"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_available_bytes{namespace=\"$namespace\"})"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{namespace=\"$namespace\",phase=~\"(Pending|Lost)\"}) by (persistentvolumeclaim) + sum(kube_persistentvolumeclaim_status_phase{namespace=\"$namespace\",phase=~\"(Lost)\"}) by (persistentvolumeclaim)"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"}/kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"} * 100)"
    },
    {
     "expr": "kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=~\"$namespace\"}"
    }
   ]
  }
 ]
}