---
apiVersion: v1
kind: Secret
metadata:
  name: infra-secrets
  namespace: default
  annotations:
    part_of: "my app"    
data:
  slack_webhook_url: cXVlIGVzcGVyYWJhcyBlbmNvbnRyYXIsIGEgbGEgQ2VuaWNpZW50YSA/Cg==