---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-infra-secrets
  labels:
    app: {{ .Release.Name }}-AllApps
    app.business.client: {{ .Values.ClientName }}
    environment: {{ .Values.environment }}
type: Opaque    
data:
  #mariadb_username: YWRtaW4K # admin
  mariadb_password: {{ randAlphaNum 32 | b64enc | quote }}
  #mariadb_root_username: cm9vdAo= # root 
  mariadb_root_password: {{ randAlphaNum 32 | b64enc | quote }}
  # Este deberia ser el real, lo genero como random para poder commitearlo sin generar un leak
  slack_webhook: {{ randAlphaNum 32 | b64enc | quote }} 