---
apiVersion: v1
kind: Service
metadata:
  name: consumer
  labels:
    app: {{ .Release.Name }}-consumer
    app.depends: {{ .Release.Name }}-rabbitmq
    environment: {{ .Values.environment }}
    app.business.client: {{ .Values.ClientName }}
  annotations:
    prometheus.io/scrape: 'true'
    filter.by.port.name: 'true'
    app: {{ .Release.Name }}-consumer
    app.depends: {{ .Release.Name }}-rabbitmq
    app.mqtt.event.trigger: {{ .Values.traceID }}    
spec:
  selector:
    app: {{ .Release.Name }}-consumer
  ports:
    - name: metrics
      protocol: TCP     
      port: 9090 

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-consumer-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-consumer-cr
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-consumer-cr-binding
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-consumer-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-consumer-cr
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: {{ .Release.Name }}-consumer
    app.depends: {{ .Release.Name }}-rabbitmq
    environment: {{ .Values.environment }}
    app.business.client: {{ .Values.ClientName }}
  annotations:
    prometheus.io/scrape: 'true'
    app: {{ .Release.Name }}-consumer
    app.depends: {{ .Release.Name }}-rabbitmq
    app.business.client: {{ .Values.ClientName }}
    app.mqtt.event.trigger: {{ .Values.traceID }}    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-consumer
      environment: {{ .Values.environment }}
      app.business.client: {{ .Values.ClientName }}      
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-consumer
        app.version: {{ .Values.consumer.image }}:{{ .Values.consumer.tag }}
        app.depends: {{ .Release.Name }}-rabbitmq
        environment: {{ .Values.environment }}
        app.business.client: {{ .Values.ClientName }}        
    spec:
      serviceAccountName: {{ .Release.Name }}-consumer-sa
      containers:
        - name: consumer
          image: {{ .Values.consumer.image }}:{{ .Values.consumer.tag }}
          imagePullPolicy: {{ .Values.consumer.imagePullPolicy }}
          env:
          - name: mqtthost
            value: {{ .Release.Name }}-rabbitmq
          - name: mqttvhost
            value: "/"
          - name: queue
            value: "infra"     
          - name: mqttuser
            value: "admin"       
          - name: mqttpass
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-rabbitmq
                key: rabbitmq-password            