---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: {{ .Release.Name }}-mariadb
    environment: {{ .Values.environment }}
    app.business.client: {{ .Values.ClientName }}
  annotations:
    prometheus.io/scrape: 'true'
    filter.by.port.name: 'true'
    app.mqtt.event.trigger: {{ .Values.traceID }}
spec:
  selector:
    app: mariadb
  ports:
    - name: http
      protocol: TCP     
      port: 3306        
      targetPort: 3306

---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: dbdump
  labels:
    app: {{ .Release.Name }}-mariadb
    environment: {{ .Values.environment }}
    app.business.client: {{ .Values.ClientName }}
  annotations:
    app.mqtt.event.trigger: {{ .Values.traceID }}
data:
  dump.sql: |-
      SET NAMES utf8;
      SET time_zone = '+00:00';
      SET foreign_key_checks = 0;
      SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';
      SET NAMES utf8mb4;
      DROP DATABASE IF EXISTS `clients`;
      CREATE DATABASE `clients` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;
      USE `clients`;
      DROP TABLE IF EXISTS `clients`;
      CREATE TABLE `clients` (
        `id` int(11) unsigned zerofill NOT NULL AUTO_INCREMENT,
        `client` varchar(50) NOT NULL,
        `archtype` varchar(20) NOT NULL,
        `hardware` varchar(20) NOT NULL,
        `product` varchar(20) NOT NULL,        
        `xdate` varchar(20) NULL,
        `license` varchar(20) NULL,
        PRIMARY KEY (`id`)
      ) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_general_ci;
      DROP DATABASE IF EXISTS `users`;
      CREATE DATABASE `users` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;
      USE `users`;
      DROP TABLE IF EXISTS `users`;
      CREATE TABLE `users` (
        `id_usuario` int(11) unsigned zerofill NOT NULL AUTO_INCREMENT,
        `username` varchar(50) NOT NULL,
        `password` varchar(50) NOT NULL,
        PRIMARY KEY (`id_usuario`)
      ) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_general_ci;

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: {{ .Release.Name }}-mariadb
    environment: {{ .Values.environment }}
    app.business.client: {{ .Values.ClientName }}
  annotations:
    prometheus.io/scrape: 'true'
    app.mqtt.event.trigger: {{ .Values.traceID }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mariadb
      environment: {{ .Values.environment }}
      app.business.client: {{ .Values.ClientName }}   
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mariadb
        environment: {{ .Values.environment }}
        app.business.client: {{ .Values.ClientName }}
      annotations:
        prometheus.io/scrape: 'true'
        app.version: {{ .Values.mariadb.image }}:{{ .Values.mariadb.tag }}
        app.mqtt.event.trigger: {{ .Values.traceID }}      
        environment: {{ .Values.environment }}        
    spec:
      containers:
        - name: mariadb
          image: {{ .Values.mariadb.image }}:{{ .Values.mariadb.tag }}
          imagePullPolicy: {{ .Values.mariadb.imagePullPolicy }}
          env:
          - name: MARIADB_DATABASE
            value: "clients"    
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-infra-secrets
                key: mariadb_root_password
          - name: MARIADB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-infra-secrets
                key: mariadb_username
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-infra-secrets
                key: mariadb_password         
          volumeMounts:
            - name: dbdump
              mountPath: /docker-entrypoint-initdb.d/dump.sql
              subPath: dump.sql           
      volumes:
        - name: dbdump
          configMap:
            name: dbdump
          