---
apiVersion: v1
kind: Secret
metadata:
  name: event-driven-architecture
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/jpradoar/event-driven-architecture.git
  project: default