---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-event-exporter-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789:role/AccessToAwsResources

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-event-exporter-cr
  namespace: default
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list", "watch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-event-exporter-cr-binding
subjects:
- kind: ServiceAccount
  name: k8s-event-exporter-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: k8s-event-exporter-cr
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-event-exporter
  namespace: default
  labels:
    app: k8s-event-exporter
    environment: development
  annotations:
    prometheus.io/scrape: 'true'
    app: k8s-event-exporter
    app.business.client: 'client-001'
    app.mqtt.event.trigger: '1234567890'    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-event-exporter
      environment: development      
  template:
    metadata:
      labels:
        app: k8s-event-exporter
        environment: development         
    spec:
      serviceAccountName: k8s-event-exporter-sa
      containers:
      - name: k8s-event-exporter
        image: jpradoar/k8s-event-exporter:1.0.0
        imagePullPolicy: Always     
#-----------------------------------------          
        resources:
          requests:
            cpu: 50m
            memory: 50Mi          
          limits:
            cpu: 150m
            memory: 150Mi
#-----------------------------------------            
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true  
          runAsNonRoot: true
          capabilities:
            drop: ["ALL"]
