---
- name: OPEN PORTS FOR DEMO
  hosts: all
  become: true
  become_method: sudo

  vars:
    OS_USER: "admin"
    KUBECONFIG_PATH: "/home/{{ OS_USER }}/.kube/config"

  tasks:

      - name: Open ports to 0.0.0.0 (DANGER ONLY FOR DEMOS)
        become_user: "{{ OS_USER }}"
        ansible.builtin.shell: |
            nohup kubectl port-forward --address 0.0.0.0 deployment/producer 5000:5000 > /tmp/kubectl_producer.log 2>&1 &
            sleep 1
            nohup kubectl port-forward --address 0.0.0.0 deployment/webserver 8080:80 > /tmp/kubectl_webserver.log 2>&1 &
            sleep 1
            nohup kubectl port-forward --address 0.0.0.0 service/mqtt-rabbitmq 15672:15672 > /tmp/kubectl_rabbitmq.log 2>&1 &
            sleep 1
            nohup kubectl -n monitoring port-forward --address 0.0.0.0 service/grafana 3000:80 > /tmp/kubectl_grafana.log 2>&1 &
            sleep 1
            nohup kubectl -n argocd  port-forward --address 0.0.0.0 service/argocd-server 8082:80 > /tmp/kubectl_argocd.log 2>&1 &
        args:
          executable: /bin/bash

      - name: Get ArgoCD initial-admin-secret
        become_user: "{{ OS_USER }}"
        ansible.builtin.shell: |
            kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
        args:
          executable: /bin/bash
        register: argocd_initial_admin_secret
        environment:

      - name: Get Grafana password
        become_user: "{{ OS_USER }}"
        ansible.builtin.shell: |
            kubectl -n monitoring get secret monitoring-grafana -o jsonpath="{.data.admin-password}" | base64 -d
        args:
          executable: /bin/bash
        register: grafana_admin_pass
        environment:


      - name: Show ArgoCD secret (port 8082)
        debug:
          msg: "ArgoCD admin password: {{ argocd_initial_admin_secret.stdout }}"

      - name: Show Grafana secret (port 3000)
        debug:
          msg: "Grafana admin password: {{ grafana_admin_pass.stdout }}"
