---
name: code checker
on:
  push:
    branches:
      - develop
    paths:
      - '03-producer/*.py'
      - '04-consumer/*.py'
      - '05-dbwriter/*.py'
      - '.github/workflows/pr_code_check.yaml'

env:
  COMMITER_NAME: 'AutoCommit'

jobs:
  code-checker:
    runs-on: ubuntu-latest
    permissions:
      contents: write         # get the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      security-events: write  # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read           # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status  
      issues: write           # to create new issues in workflows
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: pwd
      run: |
        pwd

    - name: ls -lha
      run: |
        ls -lha

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: Run Lint
      run: |
        ruff format event-driven-architecture/

    - name: Run Ruff
      run: |
        ruff check --output-format full event-driven-architecture/
