name: Terraform CI/CD
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - feat/terraform
jobs:
  terraform-cicd:
    runs-on: ubuntu-latest
    #
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose openssh-client

      - name: Start localstack
        run: docker-compose -f localstack/docker-compose.yaml up -d

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure a fake AWS provider
        run: |
          mv terraform/provider.tf{,_ori}
          cp localstack/localstack_tf_provider.tf terraform/provider.tf
          ssh-keygen -b 2048 -t rsa -f terraform/kp/demo_sshkey_tf -q -N ''

      - name: Terraform init
        run: |
          export AWS_ACCESS_KEY_ID=test
          export AWS_SECRET_ACCESS_KEY=test
          export AWS_DEFAULT_REGION=us-east-1
          export AWS_ENDPOINT_URL=http://localhost:4566
          terraform -chdir=terraform/ init          

      - name: Terraform Validate
        run: |
          terraform -chdir=terraform/  validate

      - name: Terraform Format
        continue-on-error: true
        run: |
          terraform -chdir=terraform/  fmt -check
          
      - name: Terraform Security Scan
        run: |
          docker run --rm -v $PWD/terraform/:/data  aquasec/tfsec --no-color -m CRITICAL -O /data/output.txt /data

      - name: Show TF Security Scan
        run: |
          cat $PWD/terraform/output.txt
          
      - name: Make a Terraform plan
        run: |
          terraform -chdir=terraform/ plan

      - name: Make a Real Terraform apply (in fake provider)
        run: |
          terraform -chdir=terraform/ apply --auto-approve
